FROM node:alpine

EXPOSE 5000
WORKDIR /usr/src/app
COPY . .

RUN addgroup -S appuser && adduser -S appuser -G appuser && \
    chown -R appuser:appuser /usr/src/app && \
    npm install && \
    REACT_APP_BACKEND_URL=http://localhost:8080 npm run build && \
    npm install -g serve
    
USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]
